-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 07:19:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cidade_das_carnes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cidade_das_carnes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cidade_das_carnes` DEFAULT CHARACTER SET utf8 ;
USE `db_cidade_das_carnes` ;

-- -----------------------------------------------------
-- Table `db_cidade_das_carnes`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cidade_das_carnes`.`tb_categoria` (
  `idtb_categoria` INT NOT NULL,
  `peso` DECIMAL(4,2) NOT NULL,
  `descricao` VARCHAR(50) NULL,
  PRIMARY KEY (`idtb_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cidade_das_carnes`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cidade_das_carnes`.`tb_produto` (
  `idtb_produto` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `pagamento` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `fk_tbcategoria` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idtb_produto`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`fk_tbcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`fk_tbcategoria`)
    REFERENCES `db_cidade_das_carnes`.`tb_categoria` (`idtb_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_SAFE_UPDATES = 0;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_produto (idtb_produto,nome,preco,pagamento,tipo,fk_tbcategoria) VALUES
(1,"Carne moida",19.90,"","Bovina",1),
(2,"Salsicha",9.50,"","",2),
(3,"Linguiça",11.50,"","Porco",3),
(4,"Bife de boi",29.50,"","",4),
(5,"Filé de Frango",15.85,"","",5),
(6,"Alcatra",39.50,"","",6),
(7,"Figado de frango",8.30,"","",7),
(8,"Calabresa",12.30,"","",8);

INSERT INTO tb_categoria(idtb_categoria,peso,descricao) VALUES
(1,1.2,"Coixão mole"),
(2,1.0,"Processado"),
(3,1.0,"Processado"),
(4,1.5,"Maminha em tiras"),
(5,1.0,"Carne Frango fatiada");

SELECT * FROM tb_categoria;
SELECT * FROM tb_produto WHERE preco >50;
SELECT * FROM tb_produto WHERE preco >3 AND preco <60;
SELECT * FROM tb_produto WHERE nome LIKE "%C%";
SELECT *
FROM tb_produto
INNER JOIN tb_categoria
ON tb_produto.fk_tbcategoria = tb_categoria.idtb_categoria;
SELECT tb_produto.nome, tb_categoria.descricao
FROM tb_produto
LEFT JOIN tb_categoria
ON tb_produto.fk_tbcategoria = tb_categoria.idtb_categoria;



