-- MySQL Script generated by MySQL Workbench
-- Fri Mar 12 13:02:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation_game_online` ;

-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `idtb_classe` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `habilidade` VARCHAR(20) NULL,
  `nivel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtb_classe`),
  UNIQUE INDEX `idtb_classe_UNIQUE` (`idtb_classe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `idtb_personagem` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ataque` INT UNSIGNED NOT NULL,
  `defesa` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `especial` VARCHAR(30) NULL,
  `tb_classe_idtb_classe` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtb_personagem`),
  UNIQUE INDEX `idtb_personagem_UNIQUE` (`idtb_personagem` ASC) VISIBLE,
  INDEX `fk_tb_personagem_tb_classe_idx` (`tb_classe_idtb_classe` ASC) VISIBLE,
  CONSTRAINT `fk_tb_personagem_tb_classe`
    FOREIGN KEY (`tb_classe_idtb_classe`)
    REFERENCES `db_generation_game_online`.`tb_classe` (`idtb_classe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_SAFE_UPDATES = 0;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_classe (habilidade,nivel) VALUES
("Voar",30), 
("Teletransportar",21),
("Força",25),
("Raio Laser",35),
("Magia","15");
SET SQL_MODE = '';
INSERT INTO tb_personagem (nome,ataque,defesa,especial,tb_classe_idtb_classe) VALUES
("Wanda Vision",7500,8000,"Raio Laser",1), 
("Hulk",21000,2500,"",2),
("Ciclope",1900,1150,"",3),
("Doutor Estranho",25000,19000,"Viagem no Tempo",4),
("Capitão América",4500,5000,"",5),
("Mantis",1800,1500,"Ler emoções",5),
("Super Homem",23000,20000,"Raio Laser",2),
("Tempestade",3500,1890,"Manipular a Natureza",1);

SELECT * FROM tb_classe;
SELECT * FROM tb_personagem;
SELECT * FROM tb_personagem WHERE ataque > 2000;
SELECT * FROM tb_personagem WHERE defesa >= 1000 AND defesa <=2000; 
SELECT * FROM tb_personagem WHERE nome LIKE "%C%";
SELECT *
FROM tb_personagem
INNER JOIN tb_classe
ON tb_classe.idtb_classe = tb_personagem.tb_classe_idtb_classe;
SELECT tb_personagem.nome, tb_classe.habilidade
FROM tb_personagem
INNER JOIN tb_classe 
ON tb_classe_idtb_classe = tb_personagem.tb_classe_idtb_classe;








