-- MySQL Script generated by MySQL Workbench
-- Sat Mar 13 16:21:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;
-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categoria` (
  `idtb_categoria` INT NOT NULL AUTO_INCREMENT,
  `opcional` VARCHAR(50) NULL,
  `tipo` VARCHAR(20) NULL,
  PRIMARY KEY (`idtb_categoria`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
  `idtb_pizza` INT NOT NULL,
  `sabor` VARCHAR(50) NOT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(3,2) NOT NULL,
  `descricao` VARCHAR(150) NULL,
  `fk_categoria` INT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idtb_pizza`),
  INDEX `fk_tb_pizza_tb_categoria_idx` (`fk_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pizza_tb_categoria`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `db_pizzaria_legal`.`tb_categoria` (`idtb_categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO tb_categoria (opcional,tipo) VALUES 
("Orégano e palmito","Salgada"),
("Borda de Catupiry e Azeitona","Salgada"),
("Borda de Bacon com Cheddar","Salgada"),
("Banana e maçã","Doce"),
("Borda de Morango com ninho","Doce");

ALTER TABLE tb_pizza MODIFY preco decimal(5,2);
INSERT INTO tb_pizza (idtb_pizza,sabor,tamanho,preco,descricao) VALUES 
(1,"Calabresa com cebola","Grande",32.50,"calabresa cortada em rodelas com cebola"),
(2,"Frango com Catupiry","Grande",29.99,"Frango desfiado com cobertura de catupiry"),
(3,"Portuguesa","Grande",35.00,"Presunto e mussarela com ovo e cebola"),
(4,"Romeu e Julieta","Média",21.00,"Chocolate derretido com goiabada"),
(5,"Sensação","Pequena",13.00,"Chocolate com calda de morango"),
(6,"Meia sensação e romeu e julieta","Grande",49.00,"Chocolate com calda de morango e Chocolate derretido com goiabada"),
(7,"Meia portuguesa e meia calabresa","Grande",37.00,"Presunto e mussarela com ovo e cebola e calabresa cortada em rodelas"),
(8,"Picanha com 4 queijos","Grande",50.00,"Pedaços de picanha com 4 tipos de queijo");

SELECT * FROM tb_pizza;
SELECT * FROM tb_categoria;
SELECT * FROM tb_pizza WHERE preco > 45.00;
SELECT * FROM tb_pizza WHERE sabor LIKE "%C%";
SELECT *
FROM tb_pizza
INNER JOIN tb_categoria
ON tb_pizza.fk_categoria = tb_categoria.idtb_categoria;
SELECT tb_pizza.sabor, tb_categoria.tipo
FROM tb_pizza
INNER JOIN tb_categoria
ON tb_categoria.idtb_categoria = tb_pizza.fk_categoria;


