-- MySQL Script generated by MySQL Workbench
-- Thu Mar 11 19:55:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`produtos` (
  `idprodutos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantidade` INT UNSIGNED NOT NULL,
  `tipo` VARCHAR(20) NULL DEFAULT "NULL",
  `marca` VARCHAR(20) NULL DEFAULT "NULL",
  `pagamento` VARCHAR(15) NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `faixaEtaria` VARCHAR(20) NULL DEFAULT "NULL",
  PRIMARY KEY (`idprodutos`),
  UNIQUE INDEX `idprodutos_UNIQUE` (`idprodutos` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO produtos(quantidade,pagamento,valor,endereco,tipo) VALUES (2,"Dinheiro",750.00,"Rua Abigail de Nobrega - 125 - São Paulo - SP","Tenis");
INSERT INTO produtos(quantidade,pagamento,valor,endereco,tipo) VALUES (1,"Cartão",125.00,"Rua Abel Tavares - 705 - São Paulo - SP","Eletro Domético");
INSERT INTO produtos(quantidade,pagamento,valor,endereco,tipo) VALUES (3,"Dinheiro",850.99,"Rua Antonio Cirelli - 156 - Ourinhos - PR","Tenis");
INSERT INTO produtos(quantidade,pagamento,valor,endereco,tipo) VALUES (1,"Cheque",250.80,"Rua Tereza Cristina - 666 - Rio Claro - RJ","Tenis");
INSERT INTO produtos(quantidade,pagamento,valor,endereco,tipo) VALUES (2,"Dinheiro",459.99,"Rua Narcisa - 125 - Ipanema - RJ","Lazer");
INSERT INTO produtos(quantidade,pagamento,valor,endereco,tipo) VALUES (2,"Débito",530.98,"Rua Fagundes de Andrade - 10 - Goiania - GO","Brinquedo");
INSERT INTO produtos(quantidade,pagamento,valor,endereco,tipo) VALUES (3,"Dinheiro",411.37,"Rua Princesa Isabel - 88 - Curitiba - PR","Móveis");

SELECT * FROM produtos;
SELECT * FROM produtos where valor > 500;
SELECT * FROM produtos where valor < 500;

UPDATE produtos SET marca = "Nike" WHERE idprodutos = "1";
UPDATE produtos SET marca = "Nike" WHERE idprodutos = "3";
UPDATE produtos SET marca = "Nike" WHERE idprodutos = "4";
UPDATE produtos SET faixaEtaria = "Infantil" WHERE idprodutos = "6";





